<?php

function cards_menu() {
  $items = array();
  $items['bday'] = array(
    'title' => 'happy bday',
    'page callback' => 'bday_card',
    'access callback' => TRUE,
    'type' => MENU_NORMAL_ITEM,
  );
  $items['nefew barmitzfa'] = array(
    'title' => 'happy bar nefew',
    'page callback' => 'nefew_card',
    'access callback' => TRUE,
    'type' => MENU_NORMAL_ITEM,
  );
  $items['halloween'] = array(
    'title' => 'happy halloween',
    'page callback' => 'halloween_card',
    'access callback' => TRUE,
    'type' => MENU_NORMAL_ITEM,
  );

    return $items;
}


function bday_card() {
  return "
  <ul>
    <li> happy bdayyyyyy simon</li>
  </ul>";
}

function nefew_card() {
  return "
  <ul>
    <li>nefewwww  sarah happy bar mitzvot mazel tob</li>
  </ul>";
}

function halloween_card() {
  return "
  <ul>
    <li>happily halloweeennnnnn reginald enjoy this candy corn coupon!</li>
  </ul>";
}
