<?php

function greeting_menu() {
  $items = array();
  $items ['hello_friend'] = array(
    'title' => "Hello Friend!",
    'page callback' => 'say_hello',
    'access callback' => TRUE,
    'type' => MENU_NORMAL_ITEM,
  );

  $items['goodbye'] = array(
    'title' => 'Goodbye Friend!',
    'page callback' => 'say_goodbye',
    'access callback' => TRUE,
    'type' => MENU_NORMAL_ITEM,
  );
  return $items;
}


function say_hello() {
  return '<p>Hello my dear friend! </p>';
}

// This function says goodbye to the deer friend
function say_goodbye() {
  return '<p>Goodbye my deer friend...</p>';
}
